name: publish package

on:
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt update && sudo apt install -y jq
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Use Node.js >=v16
        uses: actions/setup-node@v3
        with:
          node-version: ">=16"
          cache: "pnpm"

      - run: |
          pnpm i
      - name: Publish
        if: success()

        run: |
          PUBLISHED=$(pnpm vsce search Jiabin.fe-integration --json | jq -r '.[].versions[0].version')
          CURRENT=$(cat package.json | jq -r '.version')
          if [ "$PUBLISHED" != "$CURRENT" ]; then
            npm run deploy
          else 
            echo "PUBLISHED=$PUBLISHED   CURRENT=$CURRENT. version same skip."
          fi
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
